### ISSUE TITLE
breaking at ota_begin

### ISSUE THREAD

**Issue by muji2020** [ClaesClaes/Arduino-ESP32-BLE-OTA-iOS-SwiftUI#4]
have tried this on esp32 + ios device. but it doesn't work. it always breaks at 
esp_ota_begin(update_partition, OTA_SIZE_UNKNOWN, &otaHandler);

error response: task watchdog called at ota_begin 

...or if we add the watchdog timeout bolded below-->  the ble disconnects (it reconnects but then ota doesn't work (end failed))  

**#include <esp_task_wdt.h>**

void onWrite(BLECharacteristic *pCharacteristic)
    {
      **esp_task_wdt_init(90, false);**
      std::string rxData = pCharacteristic->getValue();
      if (!downloadFlag) { //If it's the first packet of OTA since bootup, begin OTA
        Serial.println("BeginOTA");

**Comment by ClaesClaes** [comment]
Hi @muji2020,
invoking esp_ota_begin() start a process that erases the OTA partition before writing the actual program code to it. The time it takes depends on the size of your OTA partition and CPU clock speed. I would estimate around 3-5 seconds for a partition of 1 MB and 240Mhz clock speed. The watchdog initiation in your code is set at 90 seconds, which seems excessive, try with 10 instead (although it should not be the cause to the issue you are seeing). I don't see if you are resetting the watchdog anywhere in you code example, which you should.  

So I would assume you are not feeding the watchdog quickly enough. Instead of using the esp_task_wdt Have you tried to add a "vTaskDelay( 10 );" in your loop that calls the esp_ota_begin()? This would add a small (10ms) non-blocking delay and put the task on hold and allow other tasks to run.

**Comment by VladislavSmolyanoy** [comment]
Any updates on this? Have the same issue...

**Comment by ClaesClaes** [comment]
@VladislavSmolyanoy Hi, in fact yes. I'll upload a new version within next few days.

**Comment by ClaesClaes** [comment]
@VladislavSmolyanoy . Check out new repository here: https://github.com/ClaesClaes/Arduino-ESP32-NimBLE-OTA-iOS-SwiftUI

**Comment by VladislavSmolyanoy** [comment]
@ClaesClaes Just tried it out. Seems to work like a charm! Thanks a lot!
